project:
  type: website

website:
  title: "Kirkwood Salaries"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - professors.qmd
      - adjuncts.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

